=== rladies/awesome-rladies-blogs/scripts/.entry_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "title": {"type": "string"},
    "url":   {"type": "string"},
    "rss_feed": {"type": "string"},
    "type":  {"type": "string"},
    "photo_url":   {"type": "string"},
    "description": {"type": "string"},
    "language":    {"type": "string"},
    "authors": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {"type": "string"},
            "social_media": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "twitter":      {"type": "string"},
                    "mastodon":     {"type": "string"},
                    "linkedin":     {"type": "string"},
                    "facebook":     {"type": "string"},
                    "github":       {"type": "string"},
                    "instagram":    {"type": "string"},
                    "youtube":      {"type": "string"},
                    "tiktok":       {"type": "string"},
                    "periscope":    {"type": "string"},
                    "researchgate": {"type": "string"},
                    "website":      {"type": "string"},
                    "orcid":        {"type": "string"},
                    "meetup":       {"type": "string"}
                  }
                }
              ]
            }
          },
          "required": [
            "name"
          ]
        }
      ]
    }
  },
  "required": [
    "title",
    "url",
    "type",
    "authors",
    "language"
  ]
}

=== rladies/awesome-rladies-blogs/data/content/qualityandinnovation.com.json
{
  "title": "Quality and Innovation",
  "type": "blog",
  "url": "https://qualityandinnovation.com/",
  "rss_feed": "https://qualityandinnovation.com/tag/r/feed/",
  "photo_url": "https://qualityandinnovation.com/wp-content/uploads/2024/05/espresso-labs.jpg?w=200",
  "description": "Digital Transformation & Data Science for Performance Excellence since 2008",
  "language": "en",
  "authors": [
    {
      "name": "Nicole M Radziwill",
      "social_media": [
        {
          "twitter": "nicoleradziwill",
          "bluesky": "nicoleradziwill.bsky.social",
          "website": "http://qualityandinnovation.com"
        }
      ]
    }
  ]
}

=== rladies/awesome-rladies-blogs/blogs/florenciadandrea.com.json
{
  "title": "Florencia D'Andrea",
  "type": "website",
  "url": "https://florenciadandrea.com",
  "photo_url": "https://florencia.netlify.app/about/sidebar/avatar.jpg",
  "language": "en",
  "authors": [
    {
      "name": "Florencia D'Andrea",
      "social_media": [{
        "twitter": "cantoflor_87",
        "mastodon": "@florencia@techhub.social",
        "bsky": "@florencia-dandrea.bsky.social",
        "github": "flor14",
        "orcid": "0000-0002-0041-097X",
        "linkedin": "florenciadandrea"
      }]
    }
  ]
}

=== rladies/awesome-rladies-blogs/data/content/shelkariuki.netlify.app.json
{
  "title": "Shel Kariuki's blog",
  "type": "blog",
  "url": "https://shelkariuki.netlify.app",
  "photo_url": "https://shelkariuki.netlify.app/author/avatar_hubc1f6cfd80a3e5aa5176d464d1c32c28_52181_270x270_fill_q90_lanczos_center.jpeg",
  "description": "Data Analytics Consultant based in Nairobi, Kenya",
  "language": "en",
  "authors": [
    {
      "name": "Shel Kariuki",
      "social_media": [{
        "twitter": "Shel_Kariuki",
        "github": "Shelmith-Kariuki"
      }]
    }
  ]
}

=== rladies/awesome-rladies-blogs/data/content/d4tagirl.com.json
{
  "title": "d4tagirl",
  "type": "blog",
  "url": "https://d4tagirl.com/",
  "rss_feed": "https://d4tagirl.com/feed",
  "photo_url": "https://d4tagirl.com/images/avatar.png",
  "description": "A blog about a girl who found her way into data science :)",
  "language": "en",
  "authors": [
    {
      "name": "Daniela Vázquez",
      "social_media": [
        {
          "twitter": "d4tagirl",
          "bluesky": "d4tagirl.bsky.social",
          "mastodon": "@d4tagirl@hachyderm.io",
          "linkedin": "d4tagirl",
          "github": "d4tagirl",
          "website": "https://d4tagirl.com"
        }
      ]
    }
  ]
}

=== rladies/awesome-rladies-blogs/data/content/flograttarola.com.json
{
  "title": "Site | FLORENCIA GRATTAROLA",
  "type": "blog",
  "url": "https://flograttarola.com/",
  "rss_feed": "https://flograttarola.com/index.xml",
  "photo_url": "https://flograttarola.com/media/sharing.jpg",
  "description": "Postdoc Researcher",
  "language": "en",
  "authors": [
    {
      "name": "Florencia Grattarola",
      "social_media": [
        {
          "twitter": "flograttarola",
          "bluesky": "flograttarola.bsky.social",
          "mastodon": "@flograttarola@ecoevo.social/",
          "website": "https://flograttarola.com/"
        }
      ]
    }
  ]
}

=== rladies/awesome-rladies-blogs/blogs/federicagazzelloni.netlify.app.json
{
  "title": "my blog",
  "type": "blog",
  "url": "https://federicagazzelloni.netlify.app/",
  "rss_feed": "https://federicagazzelloni.netlify.app/blog/index.xml",
  "photo_url": "https://avatars.githubusercontent.com/u/61802414",
  "description": "Data analytics, visualization and modeling with R",
  "language": "en",
  "authors": [
    {
      "name": "Federica Gazzelloni",
      "social_media": [{
         "twitter": "fgazzelloni",
         "mastodon": "@Fgazzelloni@fosstodon.org",
         "github": "fgazzelloni",
         "youtube": "Federica Gazzelloni",
         "website": "https://federicagazzelloni.netlify.app/",
         "linkedin": "fgazzelloni",
         "orcid": "0000-0002-4285-611X"
      }]
    }
  ]
}

=== rladies/awesome-rladies-blogs/data/content/do-won.github.io.json
{
  "title": "Do Won Kim",
  "type": "blog",
  "url": "https://do-won.github.io/",
  "rss_feed": "https://do-won.github.io/index.xml",
  "description": "I am a PhD candidate in Information at University of Maryland. I study computational social science and political behavior.",
  "language": "en",
  "authors": [
    {
      "name": "Do Won Kim",
      "social_media": [
        {
          "github": "DO-WON",
          "website": "do-won.github.io"
        }
      ]
    }
  ]
}

=== rladies/awesome-rladies-blogs/blogs/ivelasq.rbind.io.json
{
  "title": "%>% Dreams",
  "type": "blog",
  "url": "https://ivelasq.rbind.io/",
  "rss_feed": "https://ivelasq.rbind.io/index.xml",
  "photo_url": "https://ivelasq.rbind.io/images/avatar.jpg",
  "description": "Isabella Velásquez Personal Site on R and Analytics",
  "language": "en",
  "authors": [
    {
      "name": "Isabella Velásquez",
      "social_media": [{
        "twitter": "ivelasq3",
        "mastodon": "@ivelasq3@fosstodon.org",
        "github": "ivelasq",
        "linkedin": "ivelasq",
        "orcid": "0000-0002-7180-4095",
        "instagram": "ivelasq",
        "website": "https://ivelasq.rbind.io/"
      }]
    }
  ]
}
