=== rladies/awesome-rladies-blogs/scripts/.entry_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "title": {"type": "string"},
    "url":   {"type": "string"},
    "rss_feed": {"type": "string"},
    "type":  {"type": "string"},
    "photo_url":   {"type": "string"},
    "description": {"type": "string"},
    "language":    {"type": "string"},
    "authors": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {"type": "string"},
            "social_media": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "twitter":      {"type": "string"},
                    "mastodon":     {"type": "string"},
                    "linkedin":     {"type": "string"},
                    "facebook":     {"type": "string"},
                    "github":       {"type": "string"},
                    "instagram":    {"type": "string"},
                    "youtube":      {"type": "string"},
                    "tiktok":       {"type": "string"},
                    "periscope":    {"type": "string"},
                    "researchgate": {"type": "string"},
                    "website":      {"type": "string"},
                    "orcid":        {"type": "string"},
                    "meetup":       {"type": "string"}
                  }
                }
              ]
            }
          },
          "required": [
            "name"
          ]
        }
      ]
    }
  },
  "required": [
    "title",
    "url",
    "type",
    "authors",
    "language"
  ]
}

=== rladies/awesome-rladies-blogs/data/content/surroundedbydata.netlify.app.json
{
  "title": "Surrounded by Data", 
  "type": "blog", 
  "url": "https://surroundedbydata.netlify.app", 
  "photo_url": "https://surroundedbydata.netlify.app/about_files/Veerle_klein.jpg", 
  "description": "Stories about the data that can be found all around us, in Dutch and English",
  "language": "en (required)", 
  "authors": [ 
    {
      "name": "Veerle van Son", 
      "social_media": [{
         "twitter": "veerlevanson",
         "bluesky": "veerlevanson.bsky.social",
         "github": "veerlevanson",
         "instagram": "veerle.van.son",
         "linkedin": "veerlevanson",
         "meetup": "rladies-den-bosch"
      }]
    }
  ]
}

=== rladies/awesome-rladies-blogs/blogs/nrennie.rbind.io.json
{
  "title": "Nicola Rennie",
  "type": "blog",
  "url": "https://nrennie.rbind.io",
  "rss_feed": "https://nrennie.rbind.io/categories/r/index.xml",
  "photo_url": "https://nrennie.rbind.io/img/nicola_blue.jpg",
  "description": "Personal website, blog, and portfolio.",
  "language": "en",
  "authors": [
    {
      "name": "Nicola Rennie",
      "social_media": [{
         "twitter": "nrennie35",
         "mastodon": "@nrennie@fosstodon.org",
         "github": "nrennie",
         "linkedin": "nicola-rennie-076511b3"
      }]
    }
  ]
}

=== rladies/awesome-rladies-blogs/data/content/fernandakellyrs.com.json
{
  "title": "Estatística | Fernanda Kelly Romeiro Silva",
  "type": "blog",
  "url": "https://www.fernandakellyrs.com/",
  "rss_feed": "https://www.fernandakellyrs.com/blog-feed.xml",
  "photo_url": "https://static.parastorage.com/client/pfavico.ico",
  "description": "Quem é Fernanda Kelly? Uma mulher preta com formação em estatística e entusiasta do universo de Machine e Deep Learning.",
  "language": "pt",
  "authors": [
    {
      "name": "Fernanda Kelly Romeiro Silva",
      "social_media": [
        {
          "linkedin": "fernandakellyrs",
          "website": "https://www.fernandakellyrs.com/"
        }
      ]
    }
  ]
}

=== rladies/awesome-rladies-blogs/data/content/isabelizimm.github.io.json
{
  "title": "Isabel Zimmerman",
  "type": "blog",
  "url": "https://isabelizimm.github.io",
  "rss_feed": "https://isabelizimm.github.io/blog-r.xml",
  "photo_url": "https://isabelizimm.github.io/profile.jpg",
  "language": "en",
  "authors": [ 
    {
      "name": "Isabel Zimmerman",
      "social_media": [{
          "twitter": "@isabelizimm",
          "bluesky": "isabelizimm.bsky.social",
          "mastodon": "@isabelizimm@fosstodon.org",
          "github": "isabelizimm",
          "linkedin": "isabel-zimmerman"
      }]
    }
  ]
}

=== rladies/awesome-rladies-blogs/blogs/elenadudukina.com.json
{
  "title": "Elena Dudukina's blog", 
  "type": "blog", 
  "url": "https://elenadudukina.com",
  "rss_feed": "https://www.elenadudukina.com/category/r/index.xml", 
  "photo_url": "https://www.elenadudukina.com/author/elena-dudukina/avatar_hub94ed909de68ef2f7bd91a471236bb47_211159_270x270_fill_q90_lanczos_center.jpg", 
  "description": "I blog about Rstats, pharmacoepidemiology, women's health, causal inference, and open source Nordic data",
  "language": "en", 
  "authors": [ 
    {
      "name": "Elena Dudukina", 
      "social_media": [{
         "twitter": "evpatora",
         "mastodon": "@evpatora@mstdn.social",
         "orcid": "0000-0002-4238-049X"
      }]
    }
  ]
}

=== rladies/awesome-rladies-blogs/data/content/masalmon.eu.json
{
  "title": "Maëlle's R blog",
  "type": "blog",
  "url": "https://masalmon.eu",
  "rss_feed": "https://masalmon.eu/post/index.xml",
  "photo_url": "https://masalmon.eu/img/barbie_office.jpg",
  "description": "R(esearch) Software Engineer & Blogger based in Nancy, France",
  "language": "en",
  "authors": [
    {
      "name": "Maëlle Salmon",
      "social_media": [{
        "twitter": "ma_salmon",
        "mastodon": "@maelle@mastodon.social",
        "bluesky": "@maellesalmon.bsky.social",
        "github": "maelle",
        "orcid": "0000-0002-2815-0399"
      }]
    }
  ]
}

=== rladies/awesome-rladies-blogs/blogs/macarenaquiroga.netlify.app.json
{
  "title": "Macarena Quiroga",
  "type": "blog",
  "url": "https://macarenaquiroga.netlify.app",
  "rss_feed": "https://macarenaquiroga.netlify.app/tag/rstats/index.xml",
  "photo_url": "https://macarenaquiroga.netlify.app/author/macarena-quiroga/avatar_hu2dcaef447beb41a9ecf37ab13d81ec8c_130063_270x270_fill_q75_lanczos_center.jpg",
  "description": "Linguistics, education, and data science with R",
  "language": "es",
  "authors": [
    {
      "name": "Macarena Quiroga",
      "social_media": [{
         "twitter": "_msquiroga",
         "mastodon": "@macarenaquiroga@datasci.social",
         "github": "msquiroga89",
         "linkedin": "macarena-quiroga"
      }]
    }
  ]
}

=== rladies/awesome-rladies-blogs/data/content/juliasilge.com.json
{
  "title": "Julia Silge",
  "type": "blog",
  "url": "https://juliasilge.com",
  "rss_feed": "https://juliasilge.com/categories/rstats/index.xml",
  "photo_url": "https://github.com/juliasilge.png",
  "description": "A data science blog by Julia Silge",
  "language": "en",
  "authors": [
    {
      "name": "Julia Silge",
      "social_media": [{
         "twitter": "juliasilge",
         "mastodon": "@juliasilge@fosstodon.org",
         "bluesky": "juliasilge.com",
         "github": "juliasilge",
         "youtube": "juliasilge",
         "website": "https://juliasilge.com",
         "linkedin": "juliasilge",
         "orcid": "0000-0002-3671-836X"
      }]
    }
  ]
}
